apiVersion: v2
name: mitodl-edxapp
description: Open Edx Platform App
type: application
version: 1.0.0
appVersion: 0.1.1
# dependencies:
# - name: postgresql
#   version: 8.3.3
#   repository: https://charts.helm.sh/stable
#   condition: postgresqlChartEnabled
