apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    app.kubernetes.io/version: 13.1.9
  labels:
    app.kubernetes.io/instance: openedx
    app.kubernetes.io/name: openedx
    app.kubernetes.io/part-of: openedx
  name: openedx-config
data:
{{- range $name, $values := .Values.configs }}
  {{ $name }}: |-
    {{ toYaml $values |  nindent 4 }}
{{- end }}