---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edxapp.fullname" . }}-cms
  labels:
    app.kubernetes.io/name: cms
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "edxapp.fullname" . }}-cms
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edxapp.fullname" . }}-lms
  labels:
    app.kubernetes.io/name: lms
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "edxapp.fullname" . }}-lms
