{{- if or .Values.serviceAccount.create .Values.vault.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edxapp.serviceAccountName" . }}
  labels:
    {{- include "edxapp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
